# Generated by Django 4.1.7 on 2023-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="modified",
            field=models.BooleanField(default=False),
        ),
    ]
