# Generated by Django 4.1.7 on 2023-03-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created"]},
        ),
    ]
